### PR TITLE
Added BrainyQuote sources and updated app to automatically update quote on source change.

### PR DESCRIPTION
**Pull request by Hual**
**Added the following sources**
- BrainyQuote QotD
- BrainyQuote art QotD
- BrainyQuote funny QotD
- BrainyQuote love QotD
- BrainyQuote nature QotD

**Added internet quote updates on source change**

### CODE REVIEW

**Comment by apsun** [comment]
Thanks for the PR!

Since all of these sources are from one site, it is best to just have one "BrainyQuote" option in the provider list, and use preferences to choose which sub-category to display.

To do so, create a sub-package named `app` under your module package: `com/crossbowffs/quotelock/modules/brainyquote/app`

Then create a new activity in that package (e.g. `BrainyQuoteConfigActivity`) and implement the dropdown there. I suggest using `PreferenceFragment`, but whatever works is fine. Just use `SharedPreferences` to store the selected option.

Then change `getConfigActivity` in your module to return a reference to that activity. Your `getQuote` method should read the preferences to determine the selected sub-category and download the quote accordingly.

**Comment by Hual** [comment]
@apsun You mean somewhat like the custom quote configuration?

**Comment by apsun** [comment]
@Hual Yep. You can use that code as a reference, just replace the `ContentProvider` stuff with `SharedPreferences`.

**Comment by Hual** [comment]
Alright, I've added the activity. Design could surely be improved on, though.

**Comment by apsun** [comment]
Great! I have a lot of work on my hands IRL right now, I'll merge this when I get the chance to work on the code again.

**Comment by geeflaxx** [comment]
Pls update the german provider natune.net
It's failed to download quote

And can you add Zitate-online.de pls :D

**Comment by geeflaxx** [comment]
Maybe to much, but it would be interesting if you add a volumebar on the lockscreen too

For better Performance when you listen music

**Comment by apsun** [comment]
Thanks, I'll get around to integration now. Apologies for the very late response.

@geeflaxx Natune.net has been fixed in #17. As for the volume bar, that would belong in a different module, sorry.

**Pull request merged**
