### PR TITLE
Recommend to replace source of Hitokoto to Hitokoto.cn.

### PR DESCRIPTION
**Pull request by Yubyf**
Because it is relatively complete than the lw112's source. This one includes both **'text**' and **'from'** tag.

### CODE REVIEW

**Comment by Yubyf** [comment]
Sorry for forgetting merge from your repo before I make the next change, may I send this pull request?@apsun

**Comment by Yubyf** [comment]
Does commit above solve this problem?

**Comment by apsun** [comment]
Sure, I'd be happy to pull, but you might want to change the link in the readme too :-)

**Comment by Yubyf** [comment]
OK. Done.

**Comment by apsun** [comment]
Thanks!

**Pull request merged**
